### PR TITLE
修改配置变量pyim-directory和pyim-dcache-directory后仍然在默认位置创建pyim目录和缓存文件的问题。添加针对evil模式与pyim不兼容的探针。

### PR DESCRIPTION
**Pull request by w0lker**
如题

### CODE REVIEW

**Comment by tumashu** [comment]
merged, thanks!

**Comment by xqliu** [comment]
@tumashu Could you please help to release a new version for this PR?

Currently creating this folder will cause spacemacs update fail due to uncommit files in the spacemacs install folder.

Thanks!

**Comment by tumashu** [comment]
Add tag 1.5.2, please test it.

**Comment by xqliu** [comment]
Thanks for the update!

**Pull request merged**
